const data = [
  {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "AZ",
      "county": "Taipei",
      "amount": 500,
      "percentage": 0.071092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "Moderna",
      "county": "Taipei",
      "amount": 530,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "BNT",
      "county": "Taipei",
      "amount": 630,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "MVC",
      "county": "Taipei",
      "amount": 230,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "Other",
      "county": "Taipei",
      "amount": 330,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "AZ",
      "county": "Taipei",
      "amount": 200,
      "percentage": 0.071092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "Moderna",
      "county": "Taipei",
      "amount": 630,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "BNT",
      "county": "Taipei",
      "amount": 530,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "MVC",
      "county": "Taipei",
      "amount": 210,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "Other",
      "county": "Taipei",
      "amount": 280,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "AZ",
      "county": "Tainan",
      "amount": 310,
      "percentage": 0.071092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "Moderna",
      "county": "Tainan",
      "amount": 430,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "BNT",
      "county": "Tainan",
      "amount": 730,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "MVC",
      "county": "Tainan",
      "amount": 350,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-11",
      "vaccine": "Other",
      "county": "Tainan",
      "amount": 430,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "AZ",
      "county": "Tainan",
      "amount": 300,
      "percentage": 0.071092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "Moderna",
      "county": "Tainan",
      "amount": 430,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "BNT",
      "county": "Tainan",
      "amount": 310,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "MVC",
      "county": "Tainan",
      "amount": 150,
      "percentage": 0.075092
  }, {
      "country": "TW",
      "period": "2021-12",
      "vaccine": "Other",
      "county": "Tainan",
      "amount": 340,
      "percentage": 0.075092
  },
];