const sales = [{
    id: 1,
    region: 'North America',
    country: 'USA',
    city: 'New York',
    amount: 40,
    amount1: 2,
    month: '1',
}, {
    id: 2,
    region: 'North America',
    country: 'USA',
    city: 'New York',
    amount: 50,
    amount1: 2,
    month: '2',
}, {
    id: 3,
    region: 'North America',
    country: 'USA',
    city: 'Denver',
    amount: 35,
    amount1: 2,
    month: '1',
}, {
    id: 4,
    region: 'North America',
    country: 'USA',
    city: 'Denver',
    amount: 65,
    amount1: 2,
    month: '2',
}, {
    id: 5,
    region: 'North America',
    country: 'CAN',
    city: 'Edmonton',
    amount: 80,
    amount1: 2,
    month: '1',
}, {
    id: 6,
    region: 'South America',
    country: 'CAN',
    city: 'Edmonton',
    amount: 60,
    amount1: 2,
    month: '2',
}, {
    id: 7,
    region: 'South America',
    country: 'BRA',
    city: 'Buenos Aires',
    amount: 90,
    amount1: 2,
    month: '1',
}, {
    id: 8,
    region: 'South America',
    country: 'BRA',
    city: 'Buenos Aires',
    amount: 40,
    amount1: 2,
    month: '2',
}, {
    id: 9,
    region: 'Europe',
    country: 'GBR',
    city: 'London',
    amount: 75,
    amount1: 2,
    month: '1',
}, {
    id: 10,
    region: 'Europe',
    country: 'GBR',
    city: 'London',
    amount: 75,
    amount1: 2,
    month: '2',
}];
